---
  - name: install and start lamp servers
    yum:
      name:
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: latest

  - name: start db servers
    service:
      name: "{{ ansible_local.custom.services.db_service }}"
      state: started
      enabled: true

  - name: start web server
    service:
      name: "{{ ansible_local.custom.services.web_service }}"
      state: started
      enabled: true
