# Script for Openstack All-in-One installation
$preInstall = <<-SCRIPT
#!/bin/bash
sudo yum update -y
sudo sed -i 's/PasswordAuthentication\ no/PasswordAuthentication\ yes/g' /etc/ssh/sshd_config

SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.define :node01 do |node01_config|
      node01_config.vm.host_name = "Node01"
      node01_config.vm.network "private_network", ip:"192.168.100.11"
      node01_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
  end


  config.vm.define :node02 do |node02_config|
      node02_config.vm.host_name = "Node02"
      node02_config.vm.network "private_network", ip:"192.168.100.12"
      node02_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
  end

  config.vm.define :node03 do |node03_config|
      node03_config.vm.host_name = "Node03"
      node03_config.vm.network "private_network", ip:"192.168.100.13"
      node03_config.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1024"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
      end
  end

  config.vm.provision "shell", inline: $preInstall
end

