---
- hosts: l3-lab1
  user: vagrant
  become: yes
  tasks:
  - name: Install apache httpd but avoid starting it immediately (state=present is optional)
    apt:
      name: apache2
      state: present

  - name: start services
    service:
      name: apache2
      state: started
      enabled: yes

  - name: create index
    copy:
      content: Welcome to my web server
      dest: /var/www/html/index.html

  - name: firewalld
    ufw:
      service: http
      state: enabled
